FROM node:16-alpine
WORKDIR /app
COPY package.json /app/
RUN npm install
COPY . /app/
EXPOSE 3000   
CMD ["node", "test.js"]

# # Use Node Alpine base image
# FROM node:16-alpine

# # Set working directory
# WORKDIR /app

# # Copy app files  
# COPY . .

# # Install dependencies  
# RUN npm install

# # Expose port 3000
# EXPOSE 3000   

# # Start app
# CMD ["node", "test.js"]
