# version: '3'

# services:

#   mongodb:
#     image: mongo
#     ports:
#       - 27017:27017
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=root
#       - MONGO_INITDB_ROOT_PASSWORD=root

#   mongo-express:
#     image: mongo-express
#     ports:
#       - 8081:8081
#     environment:
#       # - ME_CONFIG_BASICAUTH_USERNAME=root
#       # - ME_CONFIG_BASICAUTH_PASSWORD=root
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=root
#       - ME_CONFIG_MONGODB_SERVER=mongodb



      
# version: '3'

# services:

#   backend:
#     build:
#       context: ./Backend
#     ports:
#       - 8000:8000

#   web:
#     build:
#       context: ./Frontend
#     ports: 
#       - 3000:3000
#     depends_on:
#       - backend
  