# FROM python:3.7-slim

# WORKDIR /app

# COPY . /app  

# RUN pip install --trusted-host pypi.python.org flask flask_cors pymongo

# EXPOSE 8000  

# CMD ["python", "main.py"]


#optimized:

FROM python:3.7-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install -r requirements.txt

COPY . /app  

EXPOSE 8000  

CMD ["python", "main.py"]